version: '3'
services:
  node-server:
    build: .
    container_name: node-server
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    depends_on: 
      - mysql
    
  mysql:
    image: mysql
    container_name: mysql-eurodb
    ports: 
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
    volumes:
      - mysql-db:/data/db
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-db: