version: '3'
services:
  node-server:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    depends_on: 
      - mysql
    
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somesuperstrongpswd
    volumes:
      - mysql-db:/data/db

volumes:
  mysql-db: