version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports: 
      - '3000:3000'
    environment:
      - PORT=3000
    depends_on: 
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    depends_on: 
      - mysql
    
  mysql:
    image: mysql
    container_name: mysql-eurodb
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
    volumes:
      - mysql-db:/data/db
      - ./server/initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-db: