version: '3'
services:
  client:
    build:
      args:
        NODE_ENV: development
    environment: 
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run start
  api:
    build: 
      args: 
        NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_NAME=EuroDB
      - DB_USER=admin
      - DB_PASSWORD=ndkv32
    command: npm run dev
  
  mysql:
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=EuroDB
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=ndkv32
    