version: '3'
services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx-eurodb
    ports:
      - '3050:80'
    depends_on:
      - client
      - api
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-eurodb
    environment:
      - PORT=3000
    depends_on: 
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api-eurodb
    environment:
      - PORT=5000
    depends_on: 
      - mysql
    
  mysql:
    image: mysql
    container_name: mysql-eurodb
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
    volumes:
      - mysql-db:/data/db
      - ./server/initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-db:
   driver: local